"""Generate src/emoji_data.inc from the `emoji` package (English, aliases, German).

Run from the repo root:  uv run python cpp/tools/gen_emoji.py
"""

import json
from pathlib import Path

import emoji

emoji.config.load_language("de")


def clean(n: str) -> str:
    return n.strip(":").replace("_", " ").lower()


rows = []
for char, data in emoji.EMOJI_DATA.items():
    if data.get("status") != emoji.STATUS["fully_qualified"]:
        continue
    names = [clean(data["en"])] + [clean(a) for a in data.get("alias", [])]
    if data.get("de"):
        names.append(clean(data["de"]))
    names = list(dict.fromkeys(names))
    rows.append(f"{{{json.dumps(char, ensure_ascii=False)}, {json.dumps('|'.join(names), ensure_ascii=False)}}},")

out = Path(__file__).resolve().parent.parent / "src" / "emoji_data.inc"
out.write_text("// Generated by tools/gen_emoji.py — do not edit.\n" + "\n".join(rows) + "\n")
print(f"{len(rows)} emoji -> {out}")
